import api from '../api/api'
export const accounts=()=>api.get('/email-accounts').then(r=>r.data.data)
export const accountConfig=()=>api.get('/email-accounts/config').then(r=>r.data.data)
export const gmailConnect=()=>api.get('/email-accounts/gmail/connect').then(r=>r.data.data)
export const addAccount=(v)=>api.post('/email-accounts',v).then(r=>r.data.data)
export const testAccount=(id)=>api.post(`/email-accounts/${id}/test`).then(r=>r.data.data)
export const removeAccount=(id)=>api.delete(`/email-accounts/${id}`).then(r=>r.data.data)
export const setDefaultAccount=(id)=>api.put(`/email-accounts/${id}/default`).then(r=>r.data.data)
export const sendEmail=(v)=>api.post('/emails/send',v).then(r=>r.data.data)
export const history=(p={})=>api.get('/emails/history',{params:p}).then(r=>r.data.data)
export const templates=()=>api.get('/templates').then(r=>r.data.data)
export const saveTemplate=(v)=>api.post('/templates',v).then(r=>r.data.data)
export const updateTemplate=(id,v)=>api.put(`/templates/${id}`,v).then(r=>r.data.data)
export const deleteTemplate=(id)=>api.delete(`/templates/${id}`).then(r=>r.data.data)
